export const barangaysJaen = [
    "Anas",
    "Bantug",
    "Bataan",
    "Bonifacio",
    "Burgos",
    "Caballero",
    "Camiling",
    "Caño",
    "Cansinala",
    "Concepcion",
    "Del Pilar",
    "Divisoria",
    "General Luna",
    "Mabini",
    "Mabutas",
    "Mabuyo",
    "Macalincag",
    "Magasawang Sapa",
    "Malabon",
    "Malaya",
    "Maligaya",
    "Magsaysay",
    "Malinta",
    "Mapagmahal",
    "Marawoy",
    "Muzon",
    "Palale",
    "Poblacion",
    "San Isidro",
    "San Juan",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santa Lucia",
    "Santo Domingo",
    "Santo Niño",
    "Santo Tomas",
    "Sumacab Este",
    "Sumacab Oeste",
    "Sulucan",
    "Sapang"
];