export const luzonPlaces = [
  // National Capital Region (NCR) – cities / municipality
  "Caloocan",
  "Las Piñas",
  "Makati",
  "Malabon",
  "Mandaluyong",
  "Manila",
  "Marikina",
  "Muntinlupa",
  "Navotas",
  "Parañaque",
  "Pasay",
  "Pasig",
  "Quezon City",
  "San Juan",
  "Taguig",
  "Pateros",

  // Central Luzon (Region III) – cities
  "Balanga",
  "Baliwag",
  "Malolos",
  "Meycauayan",
  "San Jose Del Monte",
  "Cabanatuan",
  "Gapan",
  "Science City of Muñoz",
  "Palayan",
  "San Jose City",
  "Mabalacat",
  "San Fernando",
  "Tarlac City",
  "Angeles",
  "Olongapo",

  // Central Luzon – municipalities (examples)
  "Jaen",
  "Abucay",
  "Bagac",
  "Dinalupihan",
  "Hermosa",
  "Limay",
  "Mariveles",
  "Morong",
  "Orani",
  "Orion",
  "Pilar",
  "Samal",
  "Angat",
  "Balagtas",
  "Bocaue",
  "Bulacan",
  "Samal",
  // … more municipalities in Central Luzon

  // CALABARZON (Region IV-A) – cities
  "Batangas City",
  "Lipa",
  "Tanauan",
  "Cavite City",
  "Dasmariñas",
  "Imus",
  "Tagaytay",
  "Trece Martires",
  "Biñan",
  "Cabuyao",
  "Calamba",
  "San Pablo",
  "Santa Rosa",
  "San Pedro",
  "Lucena",

  // CALABARZON – municipalities (examples)
  "Alaminos",
  "Alitagtag",
  "Bauan",
  "Calaca",
  "Calatagan",
  "Candelaria",
  "Concepcion",
  "Ibaan",
  "Lemery",
  "Lobo",
  "Lobo",
  "Mabini",
  "Nasugbu",
  "Padre Garcia",
  "San Juan",
  "San Nicolas",
  "San Pascual",
  // … more municipalities in CALABARZON

  // Ilocos Region / Cordillera / etc – cities
  "Laoag",
  "Vigan",
  "Candon",
  "Batac",
  "Alaminos (Pangasinan)",
  "Dagupan",
  "Urdaneta",
  "San Carlos (Pangasinan)",

  // Bicol (Region V) (part of Luzon island group)
  "Legazpi",
  "Naga",
  "Sorsogon City",
  "Iriga",
  "Daet",
  "Masbate City",

  // MIMAROPA and other Luzon‑group provinces (some included in Luzon group)
  "Puerto Princesa",
  "Roxas (Palawan)",
  "Calapan",
  "San Jose (Occidental Mindoro)",

  // … you would continue similarly with all municipalities and cities
];