export const luzonProvinces = [
    "Abra",
    "Apayao",
    "Aurora",
    "Bataan",
    "Batanes",
    "Batangas",
    "Benguet",
    "Bulacan",
    "Cagayan",
    "Camarines Norte",
    "Camarines Sur",
    "Catanduanes",
    "Ilocos Norte",
    "Ilocos Sur",
    "Ifugao",
    "Isabela",
    "Kalinga",
    "La Union",
    "Laguna",
    "Marinduque",
    "Masbate",
    "Mountain Province",
    "Nueva Ecija",
    "Nueva Vizcaya",
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Palawan",
    "Pampanga",
    "Pangasinan",
    "Quezon",
    "Quirino",
    "Rizal",
    "Sorsogon",
    "Tarlac",
    "Zambales"
];
